MTZProject/Models/ErrorViewModel.cs
namespace MTZProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MTZProject/Models/InputProcessVM.cs
namespace MTZProject.Models
{
    public class InputProcessVM
    {
        //NC
        public string? NivelCombustible { get; set; }
        //MV
        public string? MasaVehiculo { get; set; }
        //MC
        public string? MasaCarga { get; set; }
        //AN
        public string? AnguloInclinacion { get; set; }
        //D
        public string? DistanciaDesplazamiento { get; set; }
        //T
        public string? TiempoCompletar { get; set; }
        //RM
        public string? MaxRpm { get; set; }
        //PM
        public string? MaxPotenciaMotor { get; set; }
        //CCR
        public string? ConsumoCombustible { get; set; }

    }
}

MTZProject/Models/OutputProcessVM.cs
using System.Reflection.Metadata.Ecma335;

namespace MTZProject.Models
{
    public class OutputProcessVM
    {
        public bool Posible { get; set; }
        public double PesoNetoVehiculo { get; set; }
        public double PesoCarga { get; set; }
        public double PesoTotalVehiculo { get; set; }
        public double Velocidad { get; set; }
        public double Aceleracion { get; set; }
        public double FuerzaAtraccion { get; set; }
        public double FuerzaNeta { get; set; }
        public double FuerzaRequeridaImpulso { get; set; }
        public double PotenciaRequerida { get; set; }
        public double RevolucionesRequeridas { get; set; }
        public double CombustibleRequerido { get; set; }
    }
}

MTZProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MTZProject.Models;
using System.Diagnostics;

namespace MTZProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MTZProject/Controllers/PilotController.cs
using Microsoft.AspNetCore.Mvc;
using MTZProject.Interfaces;
using MTZProject.Logic;
using MTZProject.Models;

namespace MTZProject.Controllers
{
    public class PilotController : Controller
    {
        private IOperation _operation;
        public PilotController(IOperation operation)
        {
            _operation = operation;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(InputProcessVM dataModel)
        {
            if (ModelState.IsValid)
            {
                OutputProcessVM outputProcess = Operations.Processing(dataModel);
                return Json(outputProcess);
            }
            else
            {
                return BadRequest();
            }
        }
    }
}

MTZProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MTZProject/Views/Pilot/Index.cshtml
@model InputProcessVM;
@{

}
<div class="row">
    <form action="" method="post">
        <div class="col-5">
        <label asp-for="NivelCombustible" class="col-6">Nivel de Combustible</label>
        <input asp-for="NivelCombustible" type="text" class="form-control" name="NivelCombustible"/>

        <label asp-for="MasaVehiculo" class="col-6">Masa del Vehiculo</label>
        <input asp-for="MasaVehiculo" type="text" class="form-control" name="MasaVehiculo"/>

        <label asp-for="MasaCarga" class="col-6">Masa de la Carga</label>
        <input asp-for="MasaCarga" type="text" class="form-control" name="MasaCarga"/>

        <label asp-for="AnguloInclinacion" class="col-6">Angulo de Inclinacion</label>
        <input asp-for="AnguloInclinacion" type="text" class="form-control" name="AnguloInclinacion"/>

        <label asp-for="DistanciaDesplazamiento" class="col-6">Distancia de Desplazamiento</label>
        <input asp-for="DistanciaDesplazamiento" type="text" class="form-control" name="DistanciaDesplazamiento"/>

        <label asp-for="TiempoCompletar" class="col-6">Tiempo a completar</label>
        <input asp-for="TiempoCompletar" type="text" class="form-control" name="TiempoCompletar"/>
        
        <label asp-for="MaxRpm" class="col-6">El Maximo RPM del Motor</label>
        <input asp-for="MaxRpm" type="text" class="form-control" name="MaxRpm"/>

        <label asp-for="MaxPotenciaMotor" class="col-6">Maxima Potencia del Motor</label>
        <input asp-for="MaxPotenciaMotor" type="text" class="form-control" name="MaxPotenciaMotor" />

        <label asp-for="ConsumoCombustible" class="col-6">Nivel de Combustible</label>
        <input asp-for="ConsumoCombustible" type="text" class="form-control" name="ConsumoCombustible" />
        </div>
        <div class="my-4">
            <input class="btn btn-primary" type="submit" value="Procesar" />
        </div>
    </form>
</div>

MTZProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MTZProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MTZProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pilot" asp-action="Index">MTZProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MTZProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>